# Data Analysis with Python

## Numpy Primer 

In [2]:
import numpy as np

In [3]:
sales = [0,5,155,0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
print(sales_array)

[   0    5  155    0  518    0 1827  616  317  325]


In [4]:
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

### Properties of Numpy Array
-   ndim
-   shape
-   size
-   dtype

In [9]:
print(f"ndim =  {sales_array.ndim}")
print(f"shape = {sales_array.shape}")
print(f"size = {sales_array.size}")
print(f"dtype = {sales_array.dtype}")

ndim =  1
shape = (10,)
size = 10
dtype = int64


In [10]:
array_1d = np.array(range(10))
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array_2d = np.array([range(5), range(5,10)])
array_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
array_2d.ndim

2

In [13]:
array_2d.shape

(2, 5)

In [14]:
array_2d.size

10

In [15]:
array_2d.dtype

dtype('int64')

In [16]:
array_2d.T  # Transpose

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [17]:
array_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# list to numpy
my_list = [x*10 for x in range(10)]
print(my_list)
my_array = np.array(my_list)
print(my_array)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
[ 0 10 20 30 40 50 60 70 80 90]


In [20]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [21]:
my_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
my_array.reshape(1,10)

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [23]:
my_array.reshape(10,1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [24]:
my_array.reshape(2,5)

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [25]:
my_array.reshape(5,2)

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])